name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        go-version: ['stable', '1.17.x']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    -
      name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    -
      name: Test
      run: go test -v -race ./...
